/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAtivacoesRouteImport } from './routes/_authenticated/ativacoes'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedCentralRouteImport } from './routes/_authenticated/central'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedCreditosRouteImport } from './routes/_authenticated/creditos'
import { Route as AuthenticatedFaturamentoRouteImport } from './routes/_authenticated/faturamento'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedLicencasRouteImport } from './routes/_authenticated/licencas'
import { Route as AuthenticatedPixRouteImport } from './routes/_authenticated/pix'
import { Route as AuthenticatedRevendedoresRouteImport } from './routes/_authenticated/revendedores'
import { Route as AuthenticatedServidoresRouteImport } from './routes/_authenticated/servidores'
import { Route as AuthenticatedVencidosRouteImport } from './routes/_authenticated/vencidos'
import { Route as ApiPublicPixTokenRouteImport } from './routes/api/public/pix/$token'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtivacoesRoute = AuthenticatedAtivacoesRouteImport.update({
  id: '/ativacoes',
  path: '/ativacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentralRoute = AuthenticatedCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditosRoute = AuthenticatedCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturamentoRoute =
  AuthenticatedFaturamentoRouteImport.update({
    id: '/faturamento',
    path: '/faturamento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicencasRoute = AuthenticatedLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPixRoute = AuthenticatedPixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRevendedoresRoute =
  AuthenticatedRevendedoresRouteImport.update({
    id: '/revendedores',
    path: '/revendedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServidoresRoute = AuthenticatedServidoresRouteImport.update({
  id: '/servidores',
  path: '/servidores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVencidosRoute = AuthenticatedVencidosRouteImport.update({
  id: '/vencidos',
  path: '/vencidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPixTokenRoute = ApiPublicPixTokenRouteImport.update({
  id: '/api/public/pix/$token',
  path: '/api/public/pix/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ativacoes': typeof AuthenticatedAtivacoesRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/central': typeof AuthenticatedCentralRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/pix': typeof AuthenticatedPixRoute
  '/revendedores': typeof AuthenticatedRevendedoresRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/vencidos': typeof AuthenticatedVencidosRoute
  '/api/public/pix/$token': typeof ApiPublicPixTokenRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ativacoes': typeof AuthenticatedAtivacoesRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/central': typeof AuthenticatedCentralRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/faturamento': typeof AuthenticatedFaturamentoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/pix': typeof AuthenticatedPixRoute
  '/revendedores': typeof AuthenticatedRevendedoresRoute
  '/servidores': typeof AuthenticatedServidoresRoute
  '/vencidos': typeof AuthenticatedVencidosRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/pix/$token': typeof ApiPublicPixTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ativacoes': typeof AuthenticatedAtivacoesRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/central': typeof AuthenticatedCentralRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/creditos': typeof AuthenticatedCreditosRoute
  '/_authenticated/faturamento': typeof AuthenticatedFaturamentoRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/licencas': typeof AuthenticatedLicencasRoute
  '/_authenticated/pix': typeof AuthenticatedPixRoute
  '/_authenticated/revendedores': typeof AuthenticatedRevendedoresRoute
  '/_authenticated/servidores': typeof AuthenticatedServidoresRoute
  '/_authenticated/vencidos': typeof AuthenticatedVencidosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/pix/$token': typeof ApiPublicPixTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ativacoes'
    | '/auditoria'
    | '/backup'
    | '/central'
    | '/clientes'
    | '/configuracoes'
    | '/conta'
    | '/creditos'
    | '/faturamento'
    | '/historico'
    | '/licencas'
    | '/pix'
    | '/revendedores'
    | '/servidores'
    | '/vencidos'
    | '/api/public/pix/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/ativacoes'
    | '/auditoria'
    | '/backup'
    | '/central'
    | '/clientes'
    | '/configuracoes'
    | '/conta'
    | '/creditos'
    | '/faturamento'
    | '/historico'
    | '/licencas'
    | '/pix'
    | '/revendedores'
    | '/servidores'
    | '/vencidos'
    | '/'
    | '/api/public/pix/$token'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ativacoes'
    | '/_authenticated/auditoria'
    | '/_authenticated/backup'
    | '/_authenticated/central'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conta'
    | '/_authenticated/creditos'
    | '/_authenticated/faturamento'
    | '/_authenticated/historico'
    | '/_authenticated/licencas'
    | '/_authenticated/pix'
    | '/_authenticated/revendedores'
    | '/_authenticated/servidores'
    | '/_authenticated/vencidos'
    | '/_authenticated/'
    | '/api/public/pix/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPixTokenRoute: typeof ApiPublicPixTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ativacoes': {
      id: '/_authenticated/ativacoes'
      path: '/ativacoes'
      fullPath: '/ativacoes'
      preLoaderRoute: typeof AuthenticatedAtivacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central': {
      id: '/_authenticated/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof AuthenticatedCentralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creditos': {
      id: '/_authenticated/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AuthenticatedCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturamento': {
      id: '/_authenticated/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof AuthenticatedFaturamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licencas': {
      id: '/_authenticated/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof AuthenticatedLicencasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pix': {
      id: '/_authenticated/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof AuthenticatedPixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revendedores': {
      id: '/_authenticated/revendedores'
      path: '/revendedores'
      fullPath: '/revendedores'
      preLoaderRoute: typeof AuthenticatedRevendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servidores': {
      id: '/_authenticated/servidores'
      path: '/servidores'
      fullPath: '/servidores'
      preLoaderRoute: typeof AuthenticatedServidoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vencidos': {
      id: '/_authenticated/vencidos'
      path: '/vencidos'
      fullPath: '/vencidos'
      preLoaderRoute: typeof AuthenticatedVencidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/pix/$token': {
      id: '/api/public/pix/$token'
      path: '/api/public/pix/$token'
      fullPath: '/api/public/pix/$token'
      preLoaderRoute: typeof ApiPublicPixTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtivacoesRoute: typeof AuthenticatedAtivacoesRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedCentralRoute: typeof AuthenticatedCentralRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedCreditosRoute: typeof AuthenticatedCreditosRoute
  AuthenticatedFaturamentoRoute: typeof AuthenticatedFaturamentoRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedLicencasRoute: typeof AuthenticatedLicencasRoute
  AuthenticatedPixRoute: typeof AuthenticatedPixRoute
  AuthenticatedRevendedoresRoute: typeof AuthenticatedRevendedoresRoute
  AuthenticatedServidoresRoute: typeof AuthenticatedServidoresRoute
  AuthenticatedVencidosRoute: typeof AuthenticatedVencidosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtivacoesRoute: AuthenticatedAtivacoesRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedCentralRoute: AuthenticatedCentralRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedCreditosRoute: AuthenticatedCreditosRoute,
  AuthenticatedFaturamentoRoute: AuthenticatedFaturamentoRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedLicencasRoute: AuthenticatedLicencasRoute,
  AuthenticatedPixRoute: AuthenticatedPixRoute,
  AuthenticatedRevendedoresRoute: AuthenticatedRevendedoresRoute,
  AuthenticatedServidoresRoute: AuthenticatedServidoresRoute,
  AuthenticatedVencidosRoute: AuthenticatedVencidosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPixTokenRoute: ApiPublicPixTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
